version: '3'

networks:
  # HOST IP:
  # 192.168.111.1
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.111.0/24

services:

  back:
    container_name: phpdev_back
    image: shevaua/phpdev:latest
    volumes:
      # DYNAMIC
      - ./sites:/sites
      - ./logs/nginx:/var/log/nginx
      # STATIC
      - ./conf/nginx/templates:/etc/nginx/templates
      - ./conf/nginx/sites:/etc/nginx/sites-enabled
    ports:
      - 80:80
    entrypoint: /start.sh
    networks:
      localnet:
        ipv4_address: 192.168.111.2

  # db:
  #   container_name: phpdev_db
  #   image: "mysql:5.7"
  #   networks:
  #     localnet:
  #       ipv4_address: 192.168.111.3

  # mc:
  #   container_name: phpdev_mc
  #   image: "memcached"
  #   networks:
  #     localnet:
  #       ipv4_address: 192.168.111.4
